const elements = [{
    primary: "Creature Comforts",
    secondary: "Exhibt Poster Design",
    src: "images/poster_ad.jpg",
    width: 6,
    height: 3,
}, {
    primary: "Floral",
    secondary: "Mural Design",
    src: "images/sweet_compound.jpg",
    width: 6,
    height: 3,
}, {
    primary: "Wander, Discover, Dream",
    secondary: "3 Series Illustration",
    src: "images/3_windows.jpg",
    width: 3,
    height: 3,
}, {
    primary: "Day Time",
    secondary: "Throw Pillow Design",
    src: "images/owl_pillow.jpg",
    width: 3,
    height: 3,
}, {
    primary: "Night Time",
    secondary: "Throw Pillow Design",
    src: "images/bunny_pillow.jpg",
    width: 3,
    height: 3,
}, {
    primary: "Hunter Green",
    secondary: "Front & Back Cover Illustration",
    src: "images/turtle_cover.jpg",
    width: 4,
    height: 2,
}, {
    primary: "Tomorrow Land",
    secondary: "Poster Event Design",
    src: "images/turtle_cover.jpg",
    width: 4,
    height: 2,
}, {
    primary: "Tomorrow Land",
    secondary: "Poster Event Design",
    src: "images/tmrland_mockup.jpg",
    width: 2,
    height: 4,
}, {
    primary: "Sleeping Dogs",
    secondary: "Tote Bag Design",
    src: "images/dog_tote.jpg",
    width: 2,
    height: 4,
}, {
    primary: "Wander",
    secondary: "Digital",
    src: "images/scented_candle.jpg",
    width: 4,
    height: 3,
}, ]